
tasks:
  - init: npm install
    command: |
      export HMR_HOST=`gp url 3000`
      echo "Starting dev server..."
      npm run dev

ports:
  - port: 3000
    onOpen: open-browser

vscode:
  extensions:
    - esbenp.prettier-vscode
    - svelte.svelte-vscode
    - dracula-theme.theme-dracula
    - PKief.material-icon-theme
